//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VRSMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider : Account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceProvider()
        {
            this.ServiceProviderTypes = new HashSet<ServiceProviderType>();
            this.ServiceRequests = new HashSet<ServiceRequest>();
            this.ContactInformation = new ContactInformation();
        }
    
        public int ServiceProviderAvailabilityId { get; set; }
    
        public ContactInformation ContactInformation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceProviderType> ServiceProviderTypes { get; set; }
        public virtual ServiceProviderAvailability ServiceProviderAvailability { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequest> ServiceRequests { get; set; }
    }
}
